### ISSUE TITLE
Support for single-host topologies

### ISSUE THREAD

**Issue by blampe** [openebs/cstor-operators#432]
If I have 3 drives, I should be able to create the same topology regardless of whether those drives are attached to 3 hosts or 1 host.

For example, this works and gives me 3 pools of a single drive each:
```
    pools:
      - nodeSelector:
          kubernetes.io/hostname: "host-1"
        dataRaidGroups:
          - blockDevices:
              - blockDeviceName: "blockdevice-1"
        poolConfig:
          dataRaidGroupType: "stripe"

      - nodeSelector:
          kubernetes.io/hostname: "host-2"
        dataRaidGroups:
          - blockDevices:
              - blockDeviceName: "blockdevice-2"
        poolConfig:
          dataRaidGroupType: "stripe"

      - nodeSelector:
          kubernetes.io/hostname: "host-3"
        dataRaidGroups:
          - blockDevices:
              - blockDeviceName: "blockdevice-3"
        poolConfig:
          dataRaidGroupType: "stripe"
```

If I try to re-create the same topology on one host (maybe for local minikube testing, or maybe because I have a host with a large number of drives) it yields an error:

```
    pools:
      - nodeSelector:
          kubernetes.io/hostname: "host-1"
        dataRaidGroups:
          - blockDevices:
              - blockDeviceName: "blockdevice-1"
        poolConfig:
          dataRaidGroupType: "stripe"

      - nodeSelector:
          kubernetes.io/hostname: "host-1"
        dataRaidGroups:
          - blockDevices:
              - blockDeviceName: "blockdevice-2"
        poolConfig:
          dataRaidGroupType: "stripe"

      - nodeSelector:
          kubernetes.io/hostname: "host-1"
        dataRaidGroups:
          - blockDevices:
              - blockDeviceName: "blockdevice-3"
        poolConfig:
          dataRaidGroupType: "stripe"
```

> admission webhook "admission-webhook.cstor.openebs.io" denied the request: invalid cspc specification: invalid cspc: duplicate node host-1 entry

It seems odd to limit a host to only one pool. If we try to work around this by specifying one host with 3 raid groups, that is also an error:

```
pools:
      - nodeSelector:
          kubernetes.io/hostname: "host-1"
        dataRaidGroups:
          - blockDevices:
              - blockDeviceName: "blockdevice-1"

          - blockDevices:
              - blockDeviceName: "blockdevice-2"

          - blockDevices:
              - blockDeviceName: "blockdevice-3"
        poolConfig:
          dataRaidGroupType: "stripe"
```

> admission webhook "admission-webhook.cstor.openebs.io" denied the request: invalid cspc specification: invalid pool spec: stripe dataRaidGroups should have exactly one raidGroup

This is surprising, because `dataRaidGroups` is an array so it seems like it was intended to support multiple entries. 

AFAICT the only single-host topology supported is therefore:

```
pools:
      - nodeSelector:
          kubernetes.io/hostname: "host-1"
        dataRaidGroups:
          - blockDevices:
              - blockDeviceName: "blockdevice-1"
              - blockDeviceName: "blockdevice-2"
              - blockDeviceName: "blockdevice-3"
        poolConfig:
          dataRaidGroupType: "stripe" # or "mirror"
```

but this is fundamentally different from what was possible with 3 hosts. Namely, 3 independent pools/drives with no RAID behavior between them.
