### ISSUE TITLE
Wrong level of identation when supplying an imagePullSecrets

### ISSUE THREAD

**Issue by jam-re** [openebs/cstor-operators#434]
When specifying a custom imagePullSecrets, the generated yaml is invalid due to the ident level specified in the template (should be 8 and is instead 2) :

Example :
https://github.com/openebs/cstor-operators/blob/v3.3.x/deploy/helm/charts/templates/cspc-operator.yaml#L77

```
cstor:
  enabled: true
  csiController.attacher.image.registry: my.private.registry/
  csiController.driverRegistrar.image.registry: my.private.registry/
  csiController.provisioner.image.registry: my.private.registry/
  csiController.resizer.image.registry: my.private.registry/
  csiController.resizer.image.registry: my.private.registry/
  csiController.snapshotter.image.registry: my.private.registry/
  csiNode.driverRegistrar.image.registry: my.private.registry/
  cspcOperator.cstorPool.image.registry: my.private.registry/
  cspcOperator.cstorPoolExporter.image.registry: my.private.registry/
  cspcOperator.image.registry: my.private.registry/
  cspcOperator.poolManager.image.registry: my.private.registry/
  cstorCSIPlugin.image.registry: my.private.registry/
  cvcOperator.image.registry: my.private.registry/
  cvcOperator.target.image.registry: my.private.registry/
  cvcOperator.volumeExporter.image.registry: my.private.registry/
  cvcOperator.volumeMgmt.image.registry: my.private.registry/
  admissionServer.image.registry: my.private.registry/
  imagePullSecrets:
    - name: my-private-registry
```
