### ISSUE TITLE
no available topology found

### ISSUE THREAD

**Issue by zerowebcorp** [openebs/cstor-operators#463]
Getting this error with a fresh installation. 

`failed to provision volume with StorageClass "cstor-csi-disk": error generating accessibility requirements: no available topology found`

Installation was using helm chart.

`values.yaml`
```
cstor:
  enabled: true
  csiNode:
    kubeletDir: /var/snap/microk8s/common/var/lib/kubelet
```

```
helm upgrade --install openebs --namespace openebs openebs/openebs \
--version 3.10.0 -f openebs.yaml
```

`diskpool.yaml`

```
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "ueazrcephnp01"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-92d13577847843b0fc3c732eb2d6f5a3"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "ueazrcephnp02"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-d42fff9a7ba34f4ace7ebf7ec056aa0d"
     poolConfig:
       dataRaidGroupType: "stripe"

   - nodeSelector:
       kubernetes.io/hostname: "ewazrcephnp01"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-317d380d3988ad6a14511a3412f0541b"
     poolConfig:
       dataRaidGroupType: "stripe"
   - nodeSelector:
       kubernetes.io/hostname: "ewazrcephnp02"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-93a9a8488451b5b8eac95c86102a1d64"
     poolConfig:
       dataRaidGroupType: "stripe"
```

`storageclass.yaml`

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-csi-disk
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  # cstorPoolCluster should have the name of the CSPC
  cstorPoolCluster: cstor-disk-pool
  # replicaCount should be <= no. of CSPI created in the selected CSPC
  replicaCount: "3"
```

Upon creating a PVC, this is the error it throws

![image](https://github.com/openebs/cstor-operators/assets/914305/ead3bf2c-4235-4d50-9ca6-eb783862a623)

![image](https://github.com/openebs/cstor-operators/assets/914305/2a600a52-c2a6-4e6b-86c9-8f84590fcbcc)

![image](https://github.com/openebs/cstor-operators/assets/914305/165a8b7d-461b-4f2b-b1df-59716daf2c26)

Any clue on what could be the issue?
